export * from "./Footer";
export * from "./Header";
export * from "./GreetingsCard";
export * from "./PreviousTestsCard";
export * from "./DiagnoseCard";
export * from "./Test";
export * from "./CenterLogo";
export * from "./AllPredictions";
export * from "./InputHelper";
